app.settings={
	canvas:{
		height:1024,
		width:768,
		backgroundColor:"#f00",
		backgroundImage:"assets/img/ingame/fonds/fond0.png",
	},
	timer:0,
	gagne:false,
	finLvl:false,
	HS:{
		height:73,
		width:245,
		backgroundColor:"#e4b",
		left:540,
		top:0,
		backgroundImage:"assets/img/ingame/score/fond_score.png"
	},
	score:{
		height:73,
		width:245,
		backgroundColor:"#8df",
		left:0,
		top:0,
		backgroundImage:"assets/img/ingame/score/fond_score.png",
		value:0,
		name:"Clint",
		combo:false
	},
	life:{
		height:78,
		width:317,
		backgroundColor:"#8df",
		left:230,
		top:0,
		backgroundImage0:"assets/img/ingame/vie/vie0.png",
		backgroundImage1:"assets/img/ingame/vie/vie1.png",
		backgroundImage2:"assets/img/ingame/vie/vie2.png",
		backgroundImage3:"assets/img/ingame/vie/vie3.png",
		backgroundImage4:"assets/img/ingame/vie/vie4.png",
		backgroundImage5:"assets/img/ingame/vie/vie5.png"
	},
	listScore:[
		//--------
		{
			name:"---",
			value:000
		},
		//--------
		{
			name:"---",
			value:000
		},
		//--------
		{
			name:"---",
			value:000
		},
		//--------
		{
			name:"---",
			value:000
		},
		//--------
		{
			name:"---",
			value:000
		}
	],
	speed_level:2,
	left_wall:{
		width:190,
		height:1100,
		backgroundColor:"#0f0",
		posX:0,
		posY:-76,
		backgroundImage:"assets/img/ingame/batiments/bati_entier.png",
		backposX:0,
		backposY:3300,
	},
	right_wall:{
		width:190,
		height:1100,
		backgroundColor:"#00f",
		posX:578,
		posY:-76,
		backgroundImage:"assets/img/ingame/batiments/bati_entier.png",
		backposX:190,
		backposY:3300,
	},
	left_wall1:{
		width:190,
		height:1100,
		backgroundColor:"#0aa",
		posX:0,
		posY:-1176,
		backgroundImage:"assets/img/ingame/batiments/bati_entier.png",
		backposX:0,
		backposY:2200,
	},
	right_wall1:{
		width:190,
		height:1100,
		backgroundColor:"#aa0",
		posX:578,
		posY:-1176,
		backgroundImage:"assets/img/ingame/batiments/bati_entier.png",
		backposX:190,
		backposY:2200,
	},
	clint:{
		width:110,
		height:110,
 		posX:339,
		posY:934,
		speed:15,
		backgroundImage:"assets/img/ingame/clint/clint.png",
		backposX:-1066,
		backposY:-942,
	},
	gripped:{
		posX:0,
		posY:0
	},
	arrival:{
		posX:0,
		posY:0
	},
	nbrerobots:10,
	robot:{
		width:140,
		height:140,
		speed:2,
		backgroundImage:"assets/img/ingame/robots/robots.png",
		backposX:0,
		backposY:0,
	},
	robotbackground:[{x:-75,y:-90},{x:-75,y:-400},{x:-75,y:-730},{x:-1610,y:-90},{x:-1615,y:-410}],
	falldown:0,
	coeffalldown:0.2,
	grappin:{
		backgroundImage:"assets/img/ingame/boss/boss.png",
		backposX:-2250,
		backposY:-236,
	},
	boss:{
		backgroundImage:"assets/img/ingame/boss/boss.png",
		width:370,
		height:370,
		backposX:-55,
		backposY:-75,
		posX:225,
		posY:-500
	},
	bosstouch:0,
	zik:true,
	sons:true,
	pause: function(k){
		// space for pause
		if (k.keyCode==32) {
			switch(app.engine.start){
				case true:
					app.engine.start=false;
					break;
				case false:
					app.engine.start=true;
					break;
			}
		};
	}
};